/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Control.ControlMedico;
import Control.ControlPaciente;
import Modelo.Paciente;
import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;

import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class VentanaPost extends javax.swing.JFrame {

    public ArrayList<Modelo.Paciente> listaPacientes;
    public DefaultListModel lista = new DefaultListModel();
    String List = "";
    
    /**
     * Creates new form VentanaFinal
     */
    public VentanaPost() {
        initComponents();
        listaPacientes = new ArrayList<>();

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JlblNombre = new javax.swing.JLabel();
        jLblTelefono = new javax.swing.JLabel();
        JlblId = new javax.swing.JLabel();
        JlblNumeroId = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNumero = new javax.swing.JLabel();
        jComboTipoID = new javax.swing.JComboBox<>();
        jtxfNombre = new javax.swing.JTextField();
        Jtxttelefono = new javax.swing.JTextField();
        JtxtId = new javax.swing.JTextField();
        JlblEps = new javax.swing.JLabel();
        jComboEps = new javax.swing.JComboBox<>();
        JlblProced = new javax.swing.JLabel();
        jtxtProced = new javax.swing.JTextField();
        JlblCateg = new javax.swing.JLabel();
        jComboCateg = new javax.swing.JComboBox<>();
        JlblRecomend = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaRecomend = new javax.swing.JTextArea();
        JButtonRegistrar = new javax.swing.JButton();
        jlblEdad = new javax.swing.JLabel();
        jtxtEdad = new javax.swing.JTextField();
        jlblMedico = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListMedicos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel1.setText("Registro de Paciente");

        JlblNombre.setText("Nombre");

        jLblTelefono.setText("Telefono");

        JlblId.setText("Identificación");

        JlblNumeroId.setText("Numero de ID");

        jComboTipoID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "C.E", "T.I", "Pasaporte" }));
        jComboTipoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoIDActionPerformed(evt);
            }
        });

        JlblEps.setText("EPS");

        jComboEps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sanitas", "Salud Total", "Cruz Roja", "Cafe Salud" }));

        JlblProced.setText("procedimiento quirúrgico  ");

        JlblCateg.setText("Categoria ");

        jComboCateg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo 1", "Tipo 2", "Tipo 3", "Tipo 4" }));
        jComboCateg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCategActionPerformed(evt);
            }
        });

        JlblRecomend.setText("Recomendaciones");

        jtxaRecomend.setColumns(20);
        jtxaRecomend.setRows(5);
        jScrollPane1.setViewportView(jtxaRecomend);

        JButtonRegistrar.setText("Registrar Paciente");
        JButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonRegistrarActionPerformed(evt);
            }
        });

        jlblEdad.setText("Edad:");

        jlblMedico.setText("Medico tratante:");

        jListMedicos.setToolTipText("");
        jListMedicos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListMedicosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListMedicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JButtonRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JlblCateg)
                                .addGap(82, 82, 82)
                                .addComponent(jComboCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(JlblRecomend)
                            .addComponent(jtxtProced, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(JlblId)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(JlblNombre)
                                                .addGap(18, 18, 18)
                                                .addComponent(lblNombre))
                                            .addComponent(JlblProced))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboTipoID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtxfNombre))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(33, 33, 33)
                                                        .addComponent(jLblTelefono)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(Jtxttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(JlblNumeroId)
                                                    .addComponent(jlblEdad))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(JtxtId)
                                                    .addComponent(jtxtEdad)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(JlblEps)
                                        .addGap(52, 52, 52)
                                        .addComponent(jComboEps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero)
                                .addGap(103, 103, 103)
                                .addComponent(jlblMedico)
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlblNombre)
                            .addComponent(jLblTelefono)
                            .addComponent(jLabel6)
                            .addComponent(lblNombre)
                            .addComponent(txtNumero)
                            .addComponent(jtxfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jtxttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblMedico))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlblId)
                            .addComponent(JlblNumeroId)
                            .addComponent(jComboTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JtxtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JlblEps)
                            .addComponent(jComboEps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblEdad)
                            .addComponent(jtxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(JlblProced))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtProced, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlblCateg)
                    .addComponent(jComboCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(JlblRecomend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(JButtonRegistrar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboTipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoIDActionPerformed

    private void jComboCategActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCategActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboCategActionPerformed

    private void JButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonRegistrarActionPerformed
      VentanaPos ventanaAux = new VentanaPos();
        Modelo.Paciente paciente= new Paciente();
        Control.ControlPaciente control = new ControlPaciente(paciente,this,ventanaAux);
        control.actionPerformed(evt);
        ventanaAux.setVisible(true);
    }//GEN-LAST:event_JButtonRegistrarActionPerformed

    private void jListMedicosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListMedicosValueChanged
      Control.ControlMedico control = new ControlMedico();
      control.Lista();
    }//GEN-LAST:event_jListMedicosValueChanged

    public JButton getJButtonRegistrar() {
        return this.JButtonRegistrar;
    }
    public String lista() {
        String s = "";
        for (int i = 0; i < listaPacientes.size(); i++) {
            s = lista.getElementAt(i) + "\n";
        }
        return s = this.List;
    }

    public JTextField getJtxtId() {
        return JtxtId;
    }

    public JTextField getJtxttelefono() {
        return Jtxttelefono;
    }

    public JComboBox<String> getjComboCateg() {
        return jComboCateg;
    }

    public JComboBox<String> getjComboEps() {
        return jComboEps;
    }

    public JComboBox<String> getjComboTipoID() {
        return jComboTipoID;
    }

    public JTextArea getJtxaRecomend() {
        return jtxaRecomend;
    }

    public JTextField getJtxfNombre() {
        return jtxfNombre;
    }

    public JTextField getJtxtEdad() {
        return jtxtEdad;
    }

    public JTextField getJtxtProced() {
        return jtxtProced;
    }

    public String getList() {
        return List;
    }

   

   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonRegistrar;
    private javax.swing.JLabel JlblCateg;
    private javax.swing.JLabel JlblEps;
    private javax.swing.JLabel JlblId;
    private javax.swing.JLabel JlblNombre;
    private javax.swing.JLabel JlblNumeroId;
    private javax.swing.JLabel JlblProced;
    private javax.swing.JLabel JlblRecomend;
    private javax.swing.JTextField JtxtId;
    private javax.swing.JTextField Jtxttelefono;
    private javax.swing.JComboBox<String> jComboCateg;
    private javax.swing.JComboBox<String> jComboEps;
    private javax.swing.JComboBox<String> jComboTipoID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblTelefono;
    private javax.swing.JList<String> jListMedicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlblEdad;
    private javax.swing.JLabel jlblMedico;
    private javax.swing.JTextArea jtxaRecomend;
    private javax.swing.JTextField jtxfNombre;
    private javax.swing.JTextField jtxtEdad;
    private javax.swing.JTextField jtxtProced;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel txtNumero;
    // End of variables declaration//GEN-END:variables

    
}
